# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17lfUVAq3pkz4nD078QGoQfvLX6X82etq
"""

import pandas as pd
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

df_train=pd.read_csv('https://raw.githubusercontent.com/UNOBusinessForecasting/assignment-2-tree-based-models-anvesh232/refs/heads/main/assignment2train.csv')
df_test=pd.read_csv('https://raw.githubusercontent.com/UNOBusinessForecasting/assignment-2-tree-based-models-anvesh232/refs/heads/main/assignment2test.csv')

feature_columns = df_train.columns.drop(['id', 'DateTime', 'meal']).intersection(df_test.columns)

X_train = df_train[feature_columns]
y_train = df_train['meal']
X_test = df_test[feature_columns]
X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

model = XGBClassifier(objective='binary:logistic', eval_metric='logloss', random_state=42)
modelFit = model.fit(X_train, y_train)

pred = modelFit.predict(X_test)